# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('K', 'Kolkata'), ('C', 'Chandigarh'), ('I', 'Indore'), ('M', 'Mumbai')], max_length=20)),
                ('gl_name', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('event', models.CharField(choices=[('D', 'Street Dnace'), ('P', 'Pitch Perfect')], max_length=15)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='models2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('event', models.CharField(choices=[('S', 'Standup Soapbox'), ('R', 'Rap Wars')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preregistrations.model1'),
        ),
    ]
