# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchPerfect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_leader', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rocktaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('gender', models.CharField(max_length=6)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StreetDance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_leader', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=600)),
                ('city', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=13)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='rel',
        ),
        migrations.DeleteModel(
            name='models2',
        ),
        migrations.DeleteModel(
            name='members',
        ),
        migrations.DeleteModel(
            name='model1',
        ),
    ]
